In [322]:
import pandas as pd
import requests
import json
import datetime as dt
import matplotlib.pyplot as plt
import numpy as np

### Web Scraping was done at 8:30pm on September 26th, 2023.

## 1 For sale

In [323]:
prop_list = pd.DataFrame()

record_date = dt.date.today()

prop_list = pd.DataFrame()

In [324]:
LatitudeMax = 44.09696
LongitudeMax = -78.80222
LatitudeMin =  43.07039
LongitudeMin = -80.09449

for i in range(1,132,1):
    
    print(i)
    
    url = "https://api2.realtor.ca/Listing.svc/PropertySearch_Post"

    payload = f"ZoomLevel=10&LatitudeMax={LatitudeMax}&LongitudeMax={LongitudeMax}&LatitudeMin={LatitudeMin}&LongitudeMin={LongitudeMin}&CurrentPage={i}&Sort=6-D&PropertyTypeGroupID=1&PropertySearchTypeId=0&TransactionTypeId=2&Currency=CAD&RecordsPerPage=200&ApplicationId=1&CultureId=1&Version=7.0"
    headers = {
      'authority': 'api2.realtor.ca',
      'accept': '*/*',
      'accept-language': 'en-GB-oxendict,en-US;q=0.9,en;q=0.8',
      'cache-control': 'no-cache',
      'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
      'cookie': 'visid_incap_2269415=ns/4jOxUQM6+Mb/d8PqDGoU3EmUAAAAAQUIPAAAAAAC2A7lCcUeLl6s9HNVdtigQ; nlbi_2269415=ljrSWURMoWGA8ZtyZ/XrMgAAAAD5mhNmZOR44ApwJorkvBfW; _gcl_au=1.1.1477797097.1695692678; _gid=GA1.2.1132046867.1695692678; gig_bootstrap_3_mrQiIl6ov44s2X3j6NGWVZ9SDDtplqV7WgdcyEpGYnYxl7ygDWPQHqQqtpSiUfko=gigya-pr_ver4; ASP.NET_SessionId=x034zrinosk3mg2pgbd2kmcc; visid_incap_2271082=MIpZa5SZSR+BGM1QiDcFQaE3EmUAAAAAQUIPAAAAAADNpL/Xo1qoPmOnztaikfSO; nlbi_2271082=wCmZB7eRfkHuWseHVPrQ3QAAAABvChk8wGMQpPeS4izWXV7I; incap_ses_530_2269415=3zuHCeyrMD+8ZDHqPPFaB3BKEmUAAAAA4dAPJw6VRhyLkAWrIYN0sw==; incap_ses_530_2271082=R8LsFE9q/HSIGDPqPPFaB4VMEmUAAAAA7OBgO5WZHzbKJS3KwxNGVg==; nlbi_2271082_2147483392=3SJYVi/zkiPAi8zCVPrQ3QAAAACJm+k38e9w5uQOO1UBDdEP; reese84=3:w0+Ri+EEhSbnqnByKbYCTg==:XTu9TXjTjeB78mXIKZqYlsWajXfu3ni6hbKjXDwVSREhRF2y6rbPgHVEp8bkbunsQQBkOOnVN9SlJU7E5dLL7vx2pJFDFr9T4jg2tPFeJBiWJnsovpUU971Qh8xdEPPC3wc7+s0pyEzlcBb7Zu/R6hrJak0uALBWPUBxnU8zu7d4hAnTP0+3nvKRtlNlB9iWpMEngKaNwa4uwRxWcVEYYFuvIs7HPiDLFhx7KYTb0rrk4VyZBJnKsVVYSyNlhxImZiFpqcHGN+suwzczdBsZ+ETSyF5zRy3w41uIMOnJTfYrGEBUfyVLheMlqyGZmFbBX7Gmz0EPgme2XWVe5mzukF3ky/Ztx9srFEdGbz4SYfzIRu3lJlCXdPRU03VJJrUuK4jYihUpdweChkjdA0TZvMCM0MVCXGnE/vQlsnsramT6ho5gc0f3XteSAkl6v7mMGth/GJItutApO4uYxfc6dw==:kPhLdzev/9TY9DTNQ+nql6l86Uh5YtBZdNP4Jx8kKrc=; amp_6e403e=7iahtke8SClExT9PUYj6jX...1hb7qj2tk.1hb7qj2tk.0.0.0; glt_3_mrQiIl6ov44s2X3j6NGWVZ9SDDtplqV7WgdcyEpGYnYxl7ygDWPQHqQqtpSiUfko=st2.s.AcbHe_8zEg.FVgogTrQ5pB2u1wnHmZIIhymOLPPcoJdvB3Ng15sGgs2U_vCo5FRp4pa1wQxyXmjhXgzXimPJ_6hUsEI3lFVu2t_nz2-BR6qQI1xfLO8igWU6Jwm9njlW8LgnPaD-6_g.nR3t7WRiZ-t3TV-pHMjcwwQNxLNHbmJVwM-3aTVXOBt2sagd27092b8xCut1u0DpusIyKm14F4jUBniuckyOgQ.sc3%7CUUID%3D56adb4eb93e34110a3e5d00a2303f545; _gig_llp=googleplus; _gig_llu=%E8%B1%AA; ProfileTS=1695702593935; reese84=3:kZTbC/4fMw4HpZ+owHZBRA==:WS5UBcTv4Te9q9QejMHP1AWTjlG0BQWKEtjZ/e6bxbM6HAxIJYhTFpvHGdhukXpXml/ayk7CaaLQJ95p032ncypuwDHhk9H65/+U7AUOcYVPgodOgNcdN9czGC7iyvKvEIH+9Ia+eEOShC7lOwUoJh7URLmIRdLU3sPNUuhb+w45SkmwThjbp3bXiewuOxwRGJQZat4SZ0Ym0MQ5E2odq+xvlog8Z0ZpoKpK+oEIniVYIbczczR2OEvuBMCV/Lf9VkuWyF9g2BZr6pd4uZ80kQNRTkJXzzOi1yfxQ2SKHQfieLQ7ncWcaT4BQMMWFbIt9K1kM9Dtxk8p5pPzeLBbNXw1JynXEpu5XM7im4+Vb1EOW8JXtskXM1kfnMkbdKhtFfpXh2lT2pef/mOrS9BBGK6DsgsmWWOluooDTqtGyVRsRJYwExLXdG+l7UEBOeL5qVEGkhZmD4QAbXtFARsDBQ==:SvEJ3ULPlCWTHemKj9EtnMkPEQpRJki5d1kV2rWbsG0=; _dc_gtm_UA-12908513-11=1; nlbi_2269415_2147483392=RPO5N3W9C2c0LhBjZ/XrMgAAAABRyQEYqHL5JRz9cy2bVFTs; _ga=GA1.2.704672978.1695692678; _gali=AutoCompleteSuggestionsCon-txtMapSearchInput; _4c_=%7B%22_4c_s_%22%3A%22fZNtb9sgEMe%2FSsXrkALBBvJuyqSp0ipN0%2Fa6InCOUVNjYRJvq%2FLddzhJ3ardoijm%2Fnf5%2BZ54JmMLHVnz2lSKrRjXWtcL8gi%2FB7J%2BJin48jiSNdlWWlfGWgpgayo5E1TrxtKm4ULUyqzASrIgv5CFIFlr1BgzpwVx%2FYXxTFz0gCxulvhltBnwH%2FkPKlRIhuc%2BRX9w%2BSH%2F7kvcCNubwT%2Biw8MxOHgYg8%2FtBBBsVlsIuzYXmelJ7lMxljWbPmKlJdeVRs8YOh%2FHGVNXclZnjGBF3qY4DlBQmzbFJ7jhvEY5YmfIvXV4TNBASlMIWkPIJekEdp9jWjp70bCZs0wn%2Bavtdge7m3pRzLjbgb%2B5w0GQnA6A0rcUj6FzcEZv4qHLqWA2trO%2BIL7DEDx0Odh9TJv49AQpOLuf3vTiKS0tw%2BMKT%2FuI%2FgLEgS%2Fwpzj65PH85dPDz7vPaComayWM0suyELXBwZa2HVLhtjn3w%2Fr2dhzH5VzkbakSXA6xm6tE7UcKWFS6h9xGXCK0rQ8lasrKl2APjT3sczFL293eDkNwHobHHHtyOi9TWUxtVmYlDMdlyZiJruU02NO5umm3uHoVXkkj60q8D7%2Bw6XUY0P0PsHoPOIbrfZDGGV1xR0FVnkqpLd1qcFQ5JhVjoLRakRmJohFC6QuS6zml5gUpjHXO1FTZRlDOkWaYrykTUliHW8nYa%2BQ5S1N9UGZ3Rc4tvl5MVTGDCXIMC32%2BFj9N2zCD91i9jS1KiX0hkg%2F9aZxRGkfFGZNCvg49K2Vm6e1b%2Fxl6Ov0F%22%7D; _ga_Y07J3B53QP=GS1.1.1695698052.2.1.1695703018.31.0.0',
      'origin': 'https://www.realtor.ca',
      'pragma': 'no-cache',
      'referer': 'https://www.realtor.ca/',
      'sec-ch-ua': '"Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"macOS"',
      'sec-fetch-dest': 'empty',
      'sec-fetch-mode': 'cors',
      'sec-fetch-site': 'same-site',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'
    }

    r = requests.request("POST", url, headers=headers, data=payload)
    data = json.loads(r.text)
    
    df_temp = pd.json_normalize(data['Results'], max_level=1)
    prop_list = pd.concat([prop_list, df_temp], ignore_index=True)
    
all = prop_list[['Id','Property.Address','Land.SizeTotal','RelativeURLEn','Building.BathroomTotal','Building.Bedrooms','Building.SizeInterior','Property.Price','Property.ParkingSpaceTotal','Building.Type','Building.StoriesTotal']]
all.info()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Id                          10000 non-null  object
 1   Property.Address            10000 non-null  object
 2   Land.SizeTotal              6556 non-null   object
 3   RelativeURLEn               10000 non-null  object
 4   Building.BathroomTotal      9889 non-null   object
 5   Building.Bedrooms           9841 non-null   object
 6   Building.SizeInterior       1744 non-null   object
 7   Property.Price              10000 non-null  object
 8   Property.ParkingSpaceTotal  7063 non-null   object
 9   Building.Type               9859 non-null   object
 10  Building.StoriesTotal       10000 non-null  object
dtypes: object(11)
memory usage: 859.5+ KB

In [325]:
all.count()

Id                            10000
Property.Address              10000
Land.SizeTotal                 6556
RelativeURLEn                 10000
Building.BathroomTotal         9889
Building.Bedrooms              9841
Building.SizeInterior          1744
Property.Price                10000
Property.ParkingSpaceTotal     7063
Building.Type                  9859
Building.StoriesTotal         10000
dtype: int64

In [326]:
from pandas import json_normalize

address_dicts = all['Property.Address'].tolist()

address_df = json_normalize(address_dicts)

all = pd.concat([all.drop('Property.Address', axis=1), address_df], axis=1)

all.head()

,Id,Land.SizeTotal,RelativeURLEn,Building.BathroomTotal,Building.Bedrooms,Building.SizeInterior,Property.Price,Property.ParkingSpaceTotal,Building.Type,Building.StoriesTotal,AddressText,Longitude,Latitude,PermitShowAddress,DisseminationArea
0,26105503,x,/real-estate/26105503/125-shoreview-place-unit...,1,1,668 sqft,"$549,900",1,Apartment,1,"125 Shoreview Place|Unit #226|Stoney Creek, On...",-79.719774,43.239043,True,None
1,26105502,50 x 80.02|under 1/2 acre,/real-estate/26105502/533-east-27th-street-ham...,2,2 + 2,768 sqft,"$724,900",3,House,1,"533 EAST 27TH Street|Hamilton, Ontario L8V3H4",-79.852859,43.224551,True,None
2,26105501,39.37 x 98.43|under 1/2 acre,/real-estate/26105501/229-medici-lane-hamilton,4,4 + 1,2250 sqft,"$1,319,999",4,House,2,"229 Medici Lane|Hamilton, Ontario L9B0G8",-79.920668,43.204708,True,None
3,26105497,42.75 x 118.5|under 1/2 acre,/real-estate/26105497/4031-bloor-street-w-toronto,2,3 + 1,960 sqft,"$1,298,000",4,House,1,"4031 BLOOR Street W|Toronto, Ontario M9B1M4",-79.554876,43.637064,True,None
4,26105498,20.93 x 84.83|under 1/2 acre,/real-estate/26105498/70-laguna-village-cresce...,3,3,1561 sqft,"$824,900",NaN,Row / Townhouse,3,"70 LAGUNA VILLAGE Crescent|Hamilton, Ontario L...",-79.782885,43.171771,True,None

In [327]:
all = all.drop_duplicates()

all.count()

Id                            9985
Land.SizeTotal                6543
RelativeURLEn                 9985
Building.BathroomTotal        9874
Building.Bedrooms             9826
Building.SizeInterior         1744
Property.Price                9985
Property.ParkingSpaceTotal    7048
Building.Type                 9844
Building.StoriesTotal         9985
AddressText                   9985
Longitude                     9985
Latitude                      9985
PermitShowAddress             9985
DisseminationArea                0
dtype: int64

In [328]:
all['Address_part'] = all['AddressText'].str.split('|').str.get(1).str.strip()

# Defining a regular expression pattern to extract city, province, and postal code
pattern = r'(?P<City>[a-zA-Z\s]+), (?P<Province>[a-zA-Z\s]+) (?P<Postcode>[A-Za-z0-9]+)'

# Extracting city, province, and postal code using str.extract()
extracted = all['Address_part'].str.extract(pattern)

# Concatenating the extracted DataFrame to the original DataFrame
all = pd.concat([all, extracted], axis=1)

In [329]:
all.head()

,Id,Land.SizeTotal,RelativeURLEn,Building.BathroomTotal,Building.Bedrooms,Building.SizeInterior,Property.Price,Property.ParkingSpaceTotal,Building.Type,Building.StoriesTotal,AddressText,Longitude,Latitude,PermitShowAddress,DisseminationArea,Address_part,City,Province,Postcode
0,26105503,x,/real-estate/26105503/125-shoreview-place-unit...,1,1,668 sqft,"$549,900",1,Apartment,1,"125 Shoreview Place|Unit #226|Stoney Creek, On...",-79.719774,43.239043,True,None,Unit #226,NaN,NaN,NaN
1,26105502,50 x 80.02|under 1/2 acre,/real-estate/26105502/533-east-27th-street-ham...,2,2 + 2,768 sqft,"$724,900",3,House,1,"533 EAST 27TH Street|Hamilton, Ontario L8V3H4",-79.852859,43.224551,True,None,"Hamilton, Ontario L8V3H4",Hamilton,Ontario,L8V3H4
2,26105501,39.37 x 98.43|under 1/2 acre,/real-estate/26105501/229-medici-lane-hamilton,4,4 + 1,2250 sqft,"$1,319,999",4,House,2,"229 Medici Lane|Hamilton, Ontario L9B0G8",-79.920668,43.204708,True,None,"Hamilton, Ontario L9B0G8",Hamilton,Ontario,L9B0G8
3,26105497,42.75 x 118.5|under 1/2 acre,/real-estate/26105497/4031-bloor-street-w-toronto,2,3 + 1,960 sqft,"$1,298,000",4,House,1,"4031 BLOOR Street W|Toronto, Ontario M9B1M4",-79.554876,43.637064,True,None,"Toronto, Ontario M9B1M4",Toronto,Ontario,M9B1M4
4,26105498,20.93 x 84.83|under 1/2 acre,/real-estate/26105498/70-laguna-village-cresce...,3,3,1561 sqft,"$824,900",NaN,Row / Townhouse,3,"70 LAGUNA VILLAGE Crescent|Hamilton, Ontario L...",-79.782885,43.171771,True,None,"Hamilton, Ontario L0R1P0",Hamilton,Ontario,L0R1P0

In [373]:
# Updated list of cities in the GTA
gta_cities = [
    'Toronto', 'Mississauga', 'Brampton', 'Vaughan', 'Markham',
    'Oakville', 'Richmond Hill', 'Milton', 'Caledon', 'Pickering',
    'Ajax', 'Halton Hills', 'Newmarket', 'Aurora', 'Whitchurch-Stouffville',
    'East Gwillimbury', 'King', 'Clarington', 'Uxbridge', 'Scugog',
    'Georgetown', 'Scarborough', 'Etobicoke', 'Maple', 'North York'
]

# Filter the DataFrame to include only rows where the city is in the GTA
gta_sale = all[all['City'].isin(gta_cities)]

In [374]:
gta_sale.count()

Id                            7212
Land.SizeTotal                4128
RelativeURLEn                 7212
Building.BathroomTotal        7165
Building.Bedrooms             7139
Building.SizeInterior          522
Property.Price                7212
Property.ParkingSpaceTotal    4873
Building.Type                 7152
Building.StoriesTotal         7212
AddressText                   7212
Longitude                     7212
Latitude                      7212
PermitShowAddress             7212
DisseminationArea                0
Address_part                  7212
City                          7212
Province                      7212
Postcode                      7212
dtype: int64

In [375]:
gta_sale['City'].value_counts()

Toronto             3300
Mississauga          814
Brampton             645
Oakville             439
Vaughan              365
Markham              335
Richmond Hill        263
Milton               248
Caledon              146
Pickering            118
Ajax                 113
Halton Hills         110
Newmarket            108
Aurora                81
King                  45
Georgetown            19
Scarborough           16
East Gwillimbury      15
Uxbridge              13
Clarington             7
Etobicoke              5
Scugog                 5
North York             1
Maple                  1
Name: City, dtype: int64

In [376]:
gta_sale = gta_sale.drop(columns=['AddressText','Address_part','PermitShowAddress', 'DisseminationArea'])

In [377]:
gta_sale.head()

,Id,Land.SizeTotal,RelativeURLEn,Building.BathroomTotal,Building.Bedrooms,Building.SizeInterior,Property.Price,Property.ParkingSpaceTotal,Building.Type,Building.StoriesTotal,Longitude,Latitude,City,Province,Postcode
3,26105497,42.75 x 118.5|under 1/2 acre,/real-estate/26105497/4031-bloor-street-w-toronto,2,3 + 1,960 sqft,"$1,298,000",4,House,1,-79.554876,43.637064,Toronto,Ontario,M9B1M4
6,26105400,under 1/2 acre,/real-estate/26105400/47-jessie-street-brampton,1,2 + 0,1029.0000,"$779,900",NaN,House,1.5,-79.76548928,43.67911165,Brampton,Ontario,L6Y1L5
10,26105360,70 x 269 FT ; ** Irreg As Per Deed **,/real-estate/26105360/1750-lincolnshire-blvd-m...,7,4 + 2,NaN,"$3,990,000",10,House,,-79.5602123,43.6033232,Mississauga,Ontario,L5E2S7
11,26105356,50 x 126.23 FT,/real-estate/26105356/7626-redstone-rd-mississ...,1,3,NaN,"$968,888",8,House,1,-79.6569005,43.7168322,Mississauga,Ontario,L4T2B9
12,26105357,23 x 80.38 FT,/real-estate/26105357/265-sarah-cline-dr-oakvi...,4,3,NaN,"$1,095,000",2,Row / Townhouse,2,-79.7390355,43.4746548,Oakville,Ontario,L6M0V4

In [378]:
def process_bedrooms(value):
    value_str = str(value)
    if '+' in value_str:
        parts = value_str.split('+')
        total_bedrooms = sum(int(part) for part in parts)
        return total_bedrooms
    elif value_str.isnumeric():  
        return int(value_str)
    else:
        return value


gta_sale['Building.Bedrooms'] = gta_sale['Building.Bedrooms'].apply(process_bedrooms)

In [379]:
gta_sale.head()

,Id,Land.SizeTotal,RelativeURLEn,Building.BathroomTotal,Building.Bedrooms,Building.SizeInterior,Property.Price,Property.ParkingSpaceTotal,Building.Type,Building.StoriesTotal,Longitude,Latitude,City,Province,Postcode
3,26105497,42.75 x 118.5|under 1/2 acre,/real-estate/26105497/4031-bloor-street-w-toronto,2,4.0,960 sqft,"$1,298,000",4,House,1,-79.554876,43.637064,Toronto,Ontario,M9B1M4
6,26105400,under 1/2 acre,/real-estate/26105400/47-jessie-street-brampton,1,2.0,1029.0000,"$779,900",NaN,House,1.5,-79.76548928,43.67911165,Brampton,Ontario,L6Y1L5
10,26105360,70 x 269 FT ; ** Irreg As Per Deed **,/real-estate/26105360/1750-lincolnshire-blvd-m...,7,6.0,NaN,"$3,990,000",10,House,,-79.5602123,43.6033232,Mississauga,Ontario,L5E2S7
11,26105356,50 x 126.23 FT,/real-estate/26105356/7626-redstone-rd-mississ...,1,3.0,NaN,"$968,888",8,House,1,-79.6569005,43.7168322,Mississauga,Ontario,L4T2B9
12,26105357,23 x 80.38 FT,/real-estate/26105357/265-sarah-cline-dr-oakvi...,4,3.0,NaN,"$1,095,000",2,Row / Townhouse,2,-79.7390355,43.4746548,Oakville,Ontario,L6M0V4

In [380]:
gta_sale['Property.ParkingSpaceTotal'] = gta_sale['Property.ParkingSpaceTotal'].fillna(0)

gta_sale.head()

,Id,Land.SizeTotal,RelativeURLEn,Building.BathroomTotal,Building.Bedrooms,Building.SizeInterior,Property.Price,Property.ParkingSpaceTotal,Building.Type,Building.StoriesTotal,Longitude,Latitude,City,Province,Postcode
3,26105497,42.75 x 118.5|under 1/2 acre,/real-estate/26105497/4031-bloor-street-w-toronto,2,4.0,960 sqft,"$1,298,000",4,House,1,-79.554876,43.637064,Toronto,Ontario,M9B1M4
6,26105400,under 1/2 acre,/real-estate/26105400/47-jessie-street-brampton,1,2.0,1029.0000,"$779,900",0,House,1.5,-79.76548928,43.67911165,Brampton,Ontario,L6Y1L5
10,26105360,70 x 269 FT ; ** Irreg As Per Deed **,/real-estate/26105360/1750-lincolnshire-blvd-m...,7,6.0,NaN,"$3,990,000",10,House,,-79.5602123,43.6033232,Mississauga,Ontario,L5E2S7
11,26105356,50 x 126.23 FT,/real-estate/26105356/7626-redstone-rd-mississ...,1,3.0,NaN,"$968,888",8,House,1,-79.6569005,43.7168322,Mississauga,Ontario,L4T2B9
12,26105357,23 x 80.38 FT,/real-estate/26105357/265-sarah-cline-dr-oakvi...,4,3.0,NaN,"$1,095,000",2,Row / Townhouse,2,-79.7390355,43.4746548,Oakville,Ontario,L6M0V4

In [381]:
gta_sale.count()

Id                            7212
Land.SizeTotal                4128
RelativeURLEn                 7212
Building.BathroomTotal        7165
Building.Bedrooms             7139
Building.SizeInterior          522
Property.Price                7212
Property.ParkingSpaceTotal    7212
Building.Type                 7152
Building.StoriesTotal         7212
Longitude                     7212
Latitude                      7212
City                          7212
Province                      7212
Postcode                      7212
dtype: int64

In [382]:
gta_sale.to_excel('gta_sale.xlsx', index=False)

### 2. For Rent

In [356]:
LatitudeMax = 44.54106
LongitudeMax = -77.93900
LatitudeMin =  42.48578
LongitudeMin =42.48578

for i in range(1,60,1):
    
    print(i)
    
    url = "https://api2.realtor.ca/Listing.svc/PropertySearch_Post"

    payload = f"ZoomLevel=9&LatitudeMax={LatitudeMax}&LongitudeMax={LongitudeMax}&LatitudeMin={LatitudeMin}&LongitudeMin={LongitudeMin}&CurrentPage={i}&Sort=6-D&PropertyTypeGroupID=1&PropertySearchTypeId=0&TransactionTypeId=3&Currency=CAD&RecordsPerPage=200&ApplicationId=1&CultureId=1&Version=7.0"
    headers = {
      'authority': 'api2.realtor.ca',
      'accept': '*/*',
      'accept-language': 'en-GB-oxendict,en-US;q=0.9,en;q=0.8',
      'cache-control': 'no-cache',
      'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
      'cookie': 'visid_incap_2269415=ns/4jOxUQM6+Mb/d8PqDGoU3EmUAAAAAQUIPAAAAAAC2A7lCcUeLl6s9HNVdtigQ; nlbi_2269415=ljrSWURMoWGA8ZtyZ/XrMgAAAAD5mhNmZOR44ApwJorkvBfW; _gcl_au=1.1.1477797097.1695692678; _gid=GA1.2.1132046867.1695692678; gig_bootstrap_3_mrQiIl6ov44s2X3j6NGWVZ9SDDtplqV7WgdcyEpGYnYxl7ygDWPQHqQqtpSiUfko=gigya-pr_ver4; ASP.NET_SessionId=x034zrinosk3mg2pgbd2kmcc; visid_incap_2271082=MIpZa5SZSR+BGM1QiDcFQaE3EmUAAAAAQUIPAAAAAADNpL/Xo1qoPmOnztaikfSO; nlbi_2271082=wCmZB7eRfkHuWseHVPrQ3QAAAABvChk8wGMQpPeS4izWXV7I; incap_ses_530_2269415=3zuHCeyrMD+8ZDHqPPFaB3BKEmUAAAAA4dAPJw6VRhyLkAWrIYN0sw==; incap_ses_530_2271082=R8LsFE9q/HSIGDPqPPFaB4VMEmUAAAAA7OBgO5WZHzbKJS3KwxNGVg==; nlbi_2271082_2147483392=3SJYVi/zkiPAi8zCVPrQ3QAAAACJm+k38e9w5uQOO1UBDdEP; reese84=3:w0+Ri+EEhSbnqnByKbYCTg==:XTu9TXjTjeB78mXIKZqYlsWajXfu3ni6hbKjXDwVSREhRF2y6rbPgHVEp8bkbunsQQBkOOnVN9SlJU7E5dLL7vx2pJFDFr9T4jg2tPFeJBiWJnsovpUU971Qh8xdEPPC3wc7+s0pyEzlcBb7Zu/R6hrJak0uALBWPUBxnU8zu7d4hAnTP0+3nvKRtlNlB9iWpMEngKaNwa4uwRxWcVEYYFuvIs7HPiDLFhx7KYTb0rrk4VyZBJnKsVVYSyNlhxImZiFpqcHGN+suwzczdBsZ+ETSyF5zRy3w41uIMOnJTfYrGEBUfyVLheMlqyGZmFbBX7Gmz0EPgme2XWVe5mzukF3ky/Ztx9srFEdGbz4SYfzIRu3lJlCXdPRU03VJJrUuK4jYihUpdweChkjdA0TZvMCM0MVCXGnE/vQlsnsramT6ho5gc0f3XteSAkl6v7mMGth/GJItutApO4uYxfc6dw==:kPhLdzev/9TY9DTNQ+nql6l86Uh5YtBZdNP4Jx8kKrc=; amp_6e403e=7iahtke8SClExT9PUYj6jX...1hb7qj2tk.1hb7qj2tk.0.0.0; glt_3_mrQiIl6ov44s2X3j6NGWVZ9SDDtplqV7WgdcyEpGYnYxl7ygDWPQHqQqtpSiUfko=st2.s.AcbHe_8zEg.FVgogTrQ5pB2u1wnHmZIIhymOLPPcoJdvB3Ng15sGgs2U_vCo5FRp4pa1wQxyXmjhXgzXimPJ_6hUsEI3lFVu2t_nz2-BR6qQI1xfLO8igWU6Jwm9njlW8LgnPaD-6_g.nR3t7WRiZ-t3TV-pHMjcwwQNxLNHbmJVwM-3aTVXOBt2sagd27092b8xCut1u0DpusIyKm14F4jUBniuckyOgQ.sc3%7CUUID%3D56adb4eb93e34110a3e5d00a2303f545; _gig_llp=googleplus; _gig_llu=%E8%B1%AA; ProfileTS=1695702593935; reese84=3:kZTbC/4fMw4HpZ+owHZBRA==:WS5UBcTv4Te9q9QejMHP1AWTjlG0BQWKEtjZ/e6bxbM6HAxIJYhTFpvHGdhukXpXml/ayk7CaaLQJ95p032ncypuwDHhk9H65/+U7AUOcYVPgodOgNcdN9czGC7iyvKvEIH+9Ia+eEOShC7lOwUoJh7URLmIRdLU3sPNUuhb+w45SkmwThjbp3bXiewuOxwRGJQZat4SZ0Ym0MQ5E2odq+xvlog8Z0ZpoKpK+oEIniVYIbczczR2OEvuBMCV/Lf9VkuWyF9g2BZr6pd4uZ80kQNRTkJXzzOi1yfxQ2SKHQfieLQ7ncWcaT4BQMMWFbIt9K1kM9Dtxk8p5pPzeLBbNXw1JynXEpu5XM7im4+Vb1EOW8JXtskXM1kfnMkbdKhtFfpXh2lT2pef/mOrS9BBGK6DsgsmWWOluooDTqtGyVRsRJYwExLXdG+l7UEBOeL5qVEGkhZmD4QAbXtFARsDBQ==:SvEJ3ULPlCWTHemKj9EtnMkPEQpRJki5d1kV2rWbsG0=; _dc_gtm_UA-12908513-11=1; nlbi_2269415_2147483392=RPO5N3W9C2c0LhBjZ/XrMgAAAABRyQEYqHL5JRz9cy2bVFTs; _ga=GA1.2.704672978.1695692678; _gali=AutoCompleteSuggestionsCon-txtMapSearchInput; _4c_=%7B%22_4c_s_%22%3A%22fZNtb9sgEMe%2FSsXrkALBBvJuyqSp0ipN0%2Fa6InCOUVNjYRJvq%2FLddzhJ3ardoijm%2Fnf5%2BZ54JmMLHVnz2lSKrRjXWtcL8gi%2FB7J%2BJin48jiSNdlWWlfGWgpgayo5E1TrxtKm4ULUyqzASrIgv5CFIFlr1BgzpwVx%2FYXxTFz0gCxulvhltBnwH%2FkPKlRIhuc%2BRX9w%2BSH%2F7kvcCNubwT%2Biw8MxOHgYg8%2FtBBBsVlsIuzYXmelJ7lMxljWbPmKlJdeVRs8YOh%2FHGVNXclZnjGBF3qY4DlBQmzbFJ7jhvEY5YmfIvXV4TNBASlMIWkPIJekEdp9jWjp70bCZs0wn%2Bavtdge7m3pRzLjbgb%2B5w0GQnA6A0rcUj6FzcEZv4qHLqWA2trO%2BIL7DEDx0Odh9TJv49AQpOLuf3vTiKS0tw%2BMKT%2FuI%2FgLEgS%2Fwpzj65PH85dPDz7vPaComayWM0suyELXBwZa2HVLhtjn3w%2Fr2dhzH5VzkbakSXA6xm6tE7UcKWFS6h9xGXCK0rQ8lasrKl2APjT3sczFL293eDkNwHobHHHtyOi9TWUxtVmYlDMdlyZiJruU02NO5umm3uHoVXkkj60q8D7%2Bw6XUY0P0PsHoPOIbrfZDGGV1xR0FVnkqpLd1qcFQ5JhVjoLRakRmJohFC6QuS6zml5gUpjHXO1FTZRlDOkWaYrykTUliHW8nYa%2BQ5S1N9UGZ3Rc4tvl5MVTGDCXIMC32%2BFj9N2zCD91i9jS1KiX0hkg%2F9aZxRGkfFGZNCvg49K2Vm6e1b%2Fxl6Ov0F%22%7D; _ga_Y07J3B53QP=GS1.1.1695698052.2.1.1695703018.31.0.0',
      'origin': 'https://www.realtor.ca',
      'pragma': 'no-cache',
      'referer': 'https://www.realtor.ca/',
      'sec-ch-ua': '"Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"macOS"',
      'sec-fetch-dest': 'empty',
      'sec-fetch-mode': 'cors',
      'sec-fetch-site': 'same-site',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'
    }

    r = requests.request("POST", url, headers=headers, data=payload)
    data = json.loads(r.text)
    
    df_temp = pd.json_normalize(data['Results'], max_level=1)
    prop_list = pd.concat([prop_list, df_temp], ignore_index=True)
    
rent = prop_list[['Id','Property.Address','Land.SizeTotal','PostalCode','Property.LeaseRentUnformattedValue','RelativeURLEn','Property.OwnershipType','Building.BathroomTotal','Building.Bedrooms','Building.SizeInterior','Property.LeaseRent','Property.ParkingSpaceTotal','Building.Type','Building.StoriesTotal']]
rent.info()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 14 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Id                                  20000 non-null  object
 1   Property.Address                    20000 non-null  object
 2   Land.SizeTotal                      9262 non-null   object
 3   PostalCode                          20000 non-null  object
 4   Property.LeaseRentUnformattedValue  10000 non-null  object
 5   RelativeURLEn                       20000 non-null  object
 6   Property.OwnershipType              19278 non-null  object
 7   Building.BathroomTotal              19855 non-null  object
 8   Building.Bedrooms                   19799 non-null  object
 9   Building.SizeInterior               3245 non-null   object
 10  Property.LeaseRent                  10000 non-null  object
 11  Property.ParkingSpaceTotal          12339 non-null  object
 12  Building.Type                       19794 non-null  object
 13  Building.StoriesTotal               20000 non-null  object
dtypes: object(14)
memory usage: 2.1+ MB

In [357]:
rent.count()

Id                                    20000
Property.Address                      20000
Land.SizeTotal                         9262
PostalCode                            20000
Property.LeaseRentUnformattedValue    10000
RelativeURLEn                         20000
Property.OwnershipType                19278
Building.BathroomTotal                19855
Building.Bedrooms                     19799
Building.SizeInterior                  3245
Property.LeaseRent                    10000
Property.ParkingSpaceTotal            12339
Building.Type                         19794
Building.StoriesTotal                 20000
dtype: int64

In [358]:
rent.head()

,Id,Property.Address,Land.SizeTotal,PostalCode,Property.LeaseRentUnformattedValue,RelativeURLEn,Property.OwnershipType,Building.BathroomTotal,Building.Bedrooms,Building.SizeInterior,Property.LeaseRent,Property.ParkingSpaceTotal,Building.Type,Building.StoriesTotal
0,26105503,{'AddressText': '125 Shoreview Place|Unit #226...,x,L8E0K3,NaN,/real-estate/26105503/125-shoreview-place-unit...,Condominium,1,1,668 sqft,NaN,1,Apartment,1
1,26105502,{'AddressText': '533 EAST 27TH Street|Hamilton...,50 x 80.02|under 1/2 acre,L8V3H4,NaN,/real-estate/26105502/533-east-27th-street-ham...,Freehold,2,2 + 2,768 sqft,NaN,3,House,1
2,26105501,"{'AddressText': '229 Medici Lane|Hamilton, Ont...",39.37 x 98.43|under 1/2 acre,L9B0G8,NaN,/real-estate/26105501/229-medici-lane-hamilton,Freehold,4,4 + 1,2250 sqft,NaN,4,House,2
3,26105497,"{'AddressText': '4031 BLOOR Street W|Toronto, ...",42.75 x 118.5|under 1/2 acre,M9B1M4,NaN,/real-estate/26105497/4031-bloor-street-w-toronto,Freehold,2,3 + 1,960 sqft,NaN,4,House,1
4,26105498,{'AddressText': '70 LAGUNA VILLAGE Crescent|Ha...,20.93 x 84.83|under 1/2 acre,L0R1P0,NaN,/real-estate/26105498/70-laguna-village-cresce...,Freehold,3,3,1561 sqft,NaN,NaN,Row / Townhouse,3

In [359]:
from pandas import json_normalize

# Convert the Series of dictionaries to a list of dictionaries
address_dicts = rent['Property.Address'].tolist()

# Use json_normalize to flatten the list of dictionaries
address_df = json_normalize(address_dicts)

# Concatenate the flattened DataFrame back to the original DataFrame
rent = pd.concat([rent.drop('Property.Address', axis=1), address_df], axis=1)

rent.head()

,Id,Land.SizeTotal,PostalCode,Property.LeaseRentUnformattedValue,RelativeURLEn,Property.OwnershipType,Building.BathroomTotal,Building.Bedrooms,Building.SizeInterior,Property.LeaseRent,Property.ParkingSpaceTotal,Building.Type,Building.StoriesTotal,AddressText,Longitude,Latitude,PermitShowAddress,DisseminationArea
0,26105503,x,L8E0K3,NaN,/real-estate/26105503/125-shoreview-place-unit...,Condominium,1,1,668 sqft,NaN,1,Apartment,1,"125 Shoreview Place|Unit #226|Stoney Creek, On...",-79.719774,43.239043,True,None
1,26105502,50 x 80.02|under 1/2 acre,L8V3H4,NaN,/real-estate/26105502/533-east-27th-street-ham...,Freehold,2,2 + 2,768 sqft,NaN,3,House,1,"533 EAST 27TH Street|Hamilton, Ontario L8V3H4",-79.852859,43.224551,True,None
2,26105501,39.37 x 98.43|under 1/2 acre,L9B0G8,NaN,/real-estate/26105501/229-medici-lane-hamilton,Freehold,4,4 + 1,2250 sqft,NaN,4,House,2,"229 Medici Lane|Hamilton, Ontario L9B0G8",-79.920668,43.204708,True,None
3,26105497,42.75 x 118.5|under 1/2 acre,M9B1M4,NaN,/real-estate/26105497/4031-bloor-street-w-toronto,Freehold,2,3 + 1,960 sqft,NaN,4,House,1,"4031 BLOOR Street W|Toronto, Ontario M9B1M4",-79.554876,43.637064,True,None
4,26105498,20.93 x 84.83|under 1/2 acre,L0R1P0,NaN,/real-estate/26105498/70-laguna-village-cresce...,Freehold,3,3,1561 sqft,NaN,NaN,Row / Townhouse,3,"70 LAGUNA VILLAGE Crescent|Hamilton, Ontario L...",-79.782885,43.171771,True,None

In [360]:
rent = rent.drop_duplicates()

rent.count()

Id                                    19985
Land.SizeTotal                         9249
PostalCode                            19985
Property.LeaseRentUnformattedValue    10000
RelativeURLEn                         19985
Property.OwnershipType                19264
Building.BathroomTotal                19840
Building.Bedrooms                     19784
Building.SizeInterior                  3245
Property.LeaseRent                    10000
Property.ParkingSpaceTotal            12324
Building.Type                         19779
Building.StoriesTotal                 19985
AddressText                           19985
Longitude                             19985
Latitude                              19985
PermitShowAddress                     19985
DisseminationArea                         0
dtype: int64

In [361]:
rent = rent[rent['Property.LeaseRent'].notnull()]
rent.count()

Id                                    10000
Land.SizeTotal                         2706
PostalCode                            10000
Property.LeaseRentUnformattedValue    10000
RelativeURLEn                         10000
Property.OwnershipType                 9550
Building.BathroomTotal                 9966
Building.Bedrooms                      9958
Building.SizeInterior                  1501
Property.LeaseRent                    10000
Property.ParkingSpaceTotal             5276
Building.Type                          9935
Building.StoriesTotal                 10000
AddressText                           10000
Longitude                             10000
Latitude                              10000
PermitShowAddress                     10000
DisseminationArea                         0
dtype: int64

In [362]:
rent['Address_part'] = rent['AddressText'].str.split('|').str.get(1).str.strip()

# Defining a regular expression pattern to extract city, province, and postal code
pattern = r'(?P<City>[a-zA-Z\s]+), (?P<Province>[a-zA-Z\s]+) (?P<Postcode>[A-Za-z0-9]+)'

# Extracting city, province, and postal code using str.extract()
extracted = rent['Address_part'].str.extract(pattern)

# Concatenating the extracted DataFrame to the original DataFrame
rent = pd.concat([rent, extracted], axis=1)

In [363]:
rent.head()

,Id,Land.SizeTotal,PostalCode,Property.LeaseRentUnformattedValue,RelativeURLEn,Property.OwnershipType,Building.BathroomTotal,Building.Bedrooms,Building.SizeInterior,Property.LeaseRent,...,Building.StoriesTotal,AddressText,Longitude,Latitude,PermitShowAddress,DisseminationArea,Address_part,City,Province,Postcode
10000,26105389,78 x 253 FT,K0K1L0,1700,/real-estate/26105389/21901-loyalist-pkwy-quin...,Freehold,1,2,NaN,"$1,700/Monthly",...,1,"21901 LOYALIST PKWY|Quinte West, Ontario K0K1L0",-77.5908968,44.0527141,True,None,"Quinte West, Ontario K0K1L0",Quinte West,Ontario,K0K1L0
10001,26105386,35 x 100 FT,L8K5L4,3000,/real-estate/26105386/54-fairway-dr-hamilton-v...,Freehold,2,4,NaN,"$3,000/Monthly",...,2,"54 FAIRWAY DR|Hamilton, Ontario L8K5L4",-79.7907282,43.2136945,True,None,"Hamilton, Ontario L8K5L4",Hamilton,Ontario,L8K5L4
10002,26105387,NaN,L3B2Z2,1500,/real-estate/26105387/a-99-beatrice-st-welland,NaN,1,1,NaN,"$1,500/Monthly",...,2.5,"#A -99 BEATRICE ST|Welland, Ontario L3B2Z2",-79.2450709,42.9732278,True,None,"Welland, Ontario L3B2Z2",Welland,Ontario,L3B2Z2
10003,26105384,NaN,L8N2H8,1600,/real-estate/26105384/201-68-arkledun-ave-hami...,NaN,1,1,NaN,"$1,600/Monthly",...,2,"#201 -68 ARKLEDUN AVE|Hamilton, Ontario L8N2H8",-79.8672654,43.2465125,True,None,"Hamilton, Ontario L8N2H8",Hamilton,Ontario,L8N2H8
10004,26105380,60 x 110 FT,K9L1K6,3750,/real-estate/26105380/306-lindan-ave-smith-enn...,Freehold,2,3 + 3,NaN,"$3,750/Monthly",...,1.5,"306 LINDAN AVE|Smith-Ennismore-Lakefield, Onta...",-78.3065172,44.3576486,True,None,"Smith-Ennismore-Lakefield, Ontario K9L1K6",Lakefield,Ontario,K9L1K6

In [364]:
# Filter the DataFrame to include only rows where the city is in the GTA
gta_rent = rent[rent['City'].isin(gta_cities)]

In [365]:
gta_rent.head()

,Id,Land.SizeTotal,PostalCode,Property.LeaseRentUnformattedValue,RelativeURLEn,Property.OwnershipType,Building.BathroomTotal,Building.Bedrooms,Building.SizeInterior,Property.LeaseRent,...,Building.StoriesTotal,AddressText,Longitude,Latitude,PermitShowAddress,DisseminationArea,Address_part,City,Province,Postcode
10009,26105358,NaN,L5N7M7,3500,/real-estate/26105358/3321-snowball-rd-mississ...,Freehold,3,3,NaN,"$3,500/Monthly",...,2,"3321 SNOWBALL RD|Mississauga, Ontario L5N7M7",-79.7837474,43.5840027,True,None,"Mississauga, Ontario L5N7M7",Mississauga,Ontario,L5N7M7
10010,26105355,NaN,M6K1Z6,2650,/real-estate/26105355/210-270-dufferin-st-toro...,Condominium/Strata,1,1 + 1,NaN,"$2,650/Monthly",...,,"#210 -270 DUFFERIN ST|Toronto, Ontario M6K1Z6",-79.4274366,43.6384659,True,None,"Toronto, Ontario M6K1Z6",Toronto,Ontario,M6K1Z6
10011,26105354,NaN,L5B0M4,3275,/real-estate/26105354/4210-3883-quartz-rd-n-mi...,Condominium/Strata,2,2 + 1,NaN,"$3,275/Monthly",...,,"#4210 -3883 QUARTZ RD N|Mississauga, Ontario L...",-79.6445492,43.5837981,True,None,"Mississauga, Ontario L5B0M4",Mississauga,Ontario,L5B0M4
10012,26105352,NaN,L5B0G3,3850,/real-estate/26105352/2008-4065-brickstone-mew...,Condominium/Strata,2,3,NaN,"$3,850/Monthly",...,,"#2008 -4065 BRICKSTONE MEWS|Mississauga, Ontar...",-79.6470653,43.5860459,True,None,"Mississauga, Ontario L5B0G3",Mississauga,Ontario,L5B0G3
10013,26105347,NaN,L6P4L9,3900,/real-estate/26105347/22-davenfield-circ-bramp...,Freehold,4,4,NaN,"$3,900/Monthly",...,2,"22 DAVENFIELD CIRC|Brampton, Ontario L6P4L9",-79.6587538,43.7737049,True,None,"Brampton, Ontario L6P4L9",Brampton,Ontario,L6P4L9

In [366]:
gta_rent = gta_rent.drop(columns=['AddressText','Address_part','PermitShowAddress', 'DisseminationArea','PostalCode','Property.LeaseRent'])

In [367]:
gta_rent.head()

,Id,Land.SizeTotal,Property.LeaseRentUnformattedValue,RelativeURLEn,Property.OwnershipType,Building.BathroomTotal,Building.Bedrooms,Building.SizeInterior,Property.ParkingSpaceTotal,Building.Type,Building.StoriesTotal,Longitude,Latitude,City,Province,Postcode
10009,26105358,NaN,3500,/real-estate/26105358/3321-snowball-rd-mississ...,Freehold,3,3,NaN,2,House,2,-79.7837474,43.5840027,Mississauga,Ontario,L5N7M7
10010,26105355,NaN,2650,/real-estate/26105355/210-270-dufferin-st-toro...,Condominium/Strata,1,1 + 1,NaN,NaN,Apartment,,-79.4274366,43.6384659,Toronto,Ontario,M6K1Z6
10011,26105354,NaN,3275,/real-estate/26105354/4210-3883-quartz-rd-n-mi...,Condominium/Strata,2,2 + 1,NaN,NaN,Apartment,,-79.6445492,43.5837981,Mississauga,Ontario,L5B0M4
10012,26105352,NaN,3850,/real-estate/26105352/2008-4065-brickstone-mew...,Condominium/Strata,2,3,NaN,NaN,Apartment,,-79.6470653,43.5860459,Mississauga,Ontario,L5B0G3
10013,26105347,NaN,3900,/real-estate/26105347/22-davenfield-circ-bramp...,Freehold,4,4,NaN,3,Row / Townhouse,2,-79.6587538,43.7737049,Brampton,Ontario,L6P4L9

In [368]:
gta_rent['Property.ParkingSpaceTotal'] = gta_rent['Property.ParkingSpaceTotal'].fillna(0)

gta_rent.head()

,Id,Land.SizeTotal,Property.LeaseRentUnformattedValue,RelativeURLEn,Property.OwnershipType,Building.BathroomTotal,Building.Bedrooms,Building.SizeInterior,Property.ParkingSpaceTotal,Building.Type,Building.StoriesTotal,Longitude,Latitude,City,Province,Postcode
10009,26105358,NaN,3500,/real-estate/26105358/3321-snowball-rd-mississ...,Freehold,3,3,NaN,2,House,2,-79.7837474,43.5840027,Mississauga,Ontario,L5N7M7
10010,26105355,NaN,2650,/real-estate/26105355/210-270-dufferin-st-toro...,Condominium/Strata,1,1 + 1,NaN,0,Apartment,,-79.4274366,43.6384659,Toronto,Ontario,M6K1Z6
10011,26105354,NaN,3275,/real-estate/26105354/4210-3883-quartz-rd-n-mi...,Condominium/Strata,2,2 + 1,NaN,0,Apartment,,-79.6445492,43.5837981,Mississauga,Ontario,L5B0M4
10012,26105352,NaN,3850,/real-estate/26105352/2008-4065-brickstone-mew...,Condominium/Strata,2,3,NaN,0,Apartment,,-79.6470653,43.5860459,Mississauga,Ontario,L5B0G3
10013,26105347,NaN,3900,/real-estate/26105347/22-davenfield-circ-bramp...,Freehold,4,4,NaN,3,Row / Townhouse,2,-79.6587538,43.7737049,Brampton,Ontario,L6P4L9

In [369]:
gta_rent['Building.Bedrooms'] = gta_rent['Building.Bedrooms'].apply(process_bedrooms)

In [370]:
gta_rent.head()

,Id,Land.SizeTotal,Property.LeaseRentUnformattedValue,RelativeURLEn,Property.OwnershipType,Building.BathroomTotal,Building.Bedrooms,Building.SizeInterior,Property.ParkingSpaceTotal,Building.Type,Building.StoriesTotal,Longitude,Latitude,City,Province,Postcode
10009,26105358,NaN,3500,/real-estate/26105358/3321-snowball-rd-mississ...,Freehold,3,3.0,NaN,2,House,2,-79.7837474,43.5840027,Mississauga,Ontario,L5N7M7
10010,26105355,NaN,2650,/real-estate/26105355/210-270-dufferin-st-toro...,Condominium/Strata,1,2.0,NaN,0,Apartment,,-79.4274366,43.6384659,Toronto,Ontario,M6K1Z6
10011,26105354,NaN,3275,/real-estate/26105354/4210-3883-quartz-rd-n-mi...,Condominium/Strata,2,3.0,NaN,0,Apartment,,-79.6445492,43.5837981,Mississauga,Ontario,L5B0M4
10012,26105352,NaN,3850,/real-estate/26105352/2008-4065-brickstone-mew...,Condominium/Strata,2,3.0,NaN,0,Apartment,,-79.6470653,43.5860459,Mississauga,Ontario,L5B0G3
10013,26105347,NaN,3900,/real-estate/26105347/22-davenfield-circ-bramp...,Freehold,4,4.0,NaN,3,Row / Townhouse,2,-79.6587538,43.7737049,Brampton,Ontario,L6P4L9

In [ ]:
#gta_rent = gta_rent.dropna(subset=['Building.BathroomTotal', 'Building.Bedrooms'])

In [ ]:
#mask = (
    #(gta_rent['Building.BathroomTotal'].notnull()) & (gta_rent['Building.BathroomTotal'] != 0) &
    #(gta_rent['Building.Bedrooms'].notnull()) & (gta_rent['Building.Bedrooms'] != 0)
)

#gta_rent = gta_rent[mask]

In [371]:
gta_rent.to_excel('gta_rent.xlsx', index=False)